[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_port = COM24
monitor_port = COM24
build_flags = 
    -DPC_NO_BITSCAN=1
    -DPC_NO_HW_CRC32=1
    -DARDUINO_LOOP_STACK_SIZE=16384
